### ISSUE TITLE
version of hound required by claxon does not compile

### ISSUE THREAD

**Issue by programLyrique** [ruud-v-a/claxon#1]
Latest version of claxon requires hound 0.4.0, which does not compile.

I get the following errors:

```
Compiling hound v0.4.0
path/.cargo/registry/src/github.com-88ac128001ac3a9a/hound-0.4.0/src/lib.rs:84:5: 84:81 error: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
path/.cargo/registry/src/github.com-88ac128001ac3a9a/hound-0.4.0/src/lib.rs:84     fn read<R: io::Read>(reader: &mut R, bytes: u16, bits: u16) -> Result<Self>;
                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
path/.cargo/registry/src/github.com-88ac128001ac3a9a/hound-0.4.0/src/lib.rs:84:5: 84:81 help: run `rustc --explain E0277` to see a detailed explanation
path/.cargo/registry/src/github.com-88ac128001ac3a9a/hound-0.4.0/src/lib.rs:84:5: 84:81 note: `Self` does not have a constant size known at compile-time
path/.cargo/registry/src/github.com-88ac128001ac3a9a/hound-0.4.0/src/lib.rs:84:5: 84:81 note: required by `core::result::Result`
error: aborting due to previous error
Could not compile `hound`.

```

I'm using rust 1.7.0

**Comment by ruud-v-a** [comment]
Can you run `cargo update -p hound`? Also, which version of Claxon are you using? Quite a few things have changed on master [since v0.1.0](https://github.com/ruud-v-a/claxon/compare/v0.1.0...master) but I haven’t pushed anything to crates.io yet.

**Comment by programLyrique** [comment]
I'm using version 0.1.0 of claxon, the one on crates.io. So when I said "latest", I meant latest on crates.io.

I have two versions of hound: 0.4.0 required by claxon 0.1.0, and 1.1.0

I think I'm going to use the latest version of claxon in the git repository, instead of the one on crates.io

**Comment by ruud-v-a** [comment]
Ah right, Claxon 0.1.0 requires `hound = "0.4.0"`, which means Cargo considers it incompatible with Hound 1.0 and 1.1. For now you are probably better off using `master` indeed. It needs a bit more polish and then I’ll release a new version on crates.io.
